# Generated by Django 5.1.3 on 2024-12-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Aguardando pagamento'), ('awaiting_approval', 'Aguardando aprovação'), ('paid', 'Pago'), ('rejected', 'Negado')], default='awaiting_payment', max_length=20),
        ),
    ]
