# Generated by Django 5.1.3 on 2024-12-27 19:10

import agua.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agua', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to=agua.models.user_receipts_path),
        ),
    ]
