# Generated by Django 5.1.5 on 2025-03-18 15:19

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('awaiting_payment', 'Aguardando pagamento'), ('awaiting_approval', 'Aguardando aprovação'), ('paid', 'Pago'), ('rejected', 'Negado')], default='awaiting_payment', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=payments.models.user_receipts_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
