# Generated by Django 5.1.5 on 2025-03-23 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterWell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('nature', models.CharField(blank=True, max_length=100, null=True)),
                ('ne', models.FloatField(blank=True, null=True)),
                ('nd', models.FloatField(blank=True, null=True)),
                ('flow_rate', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('capacity', models.FloatField()),
                ('current_month_usage', models.FloatField(default=0.0)),
                ('current_kwh_consumption', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='water_wells', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterWellUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('water_usage', models.FloatField()),
                ('kwh_consumption', models.FloatField()),
                ('location', models.CharField(max_length=100)),
                ('water_well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.waterwell')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
