# Generated by Django 5.1.5 on 2025-03-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterwell',
            name='current_usage',
        ),
        migrations.AddField(
            model_name='waterwell',
            name='current_kwh_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='waterwell',
            name='current_month_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='waterwellusage',
            name='kwh_consumption',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
