# Generated by Django 5.1.5 on 2025-03-24 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterwell',
            options={'verbose_name': 'Poço de Água', 'verbose_name_plural': 'Poços de Água'},
        ),
        migrations.AlterModelOptions(
            name='waterwellusage',
            options={'ordering': ['-date'], 'verbose_name': 'Uso do Poço', 'verbose_name_plural': 'Usos dos Poços'},
        ),
        migrations.AddField(
            model_name='waterwell',
            name='original_crs',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='waterwell',
            name='original_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterwell',
            name='original_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterwell',
            name='capacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='waterwell',
            index=models.Index(fields=['latitude', 'longitude'], name='stats_water_latitud_9301ed_idx'),
        ),
        migrations.AddIndex(
            model_name='waterwell',
            index=models.Index(fields=['public_id'], name='stats_water_public__ca47cb_idx'),
        ),
    ]
